export const users = [
    {
      id: "1",
      name: "John",
      surname: "Smith",
      email: "john.smith@example.com",
      gpa: 3.5,
      favClasses: [],
    },
    {
      id: "2",
      name: "Emma",
      surname: "Johnson",
      email: "emma.johnson@example.com",
      gpa: 3.8,
      favClasses: [],
    },
    {
      id: "3",
      name: "Michael",
      surname: "Williams",
      email: "michael.williams@example.com",
      gpa: 3.2,
      favClasses: [],
    },
    {
      id: "4",
      name: "Sophia",
      surname: "Brown",
      email: "sophia.brown@example.com",
      gpa: 3.9,
      favClasses: [],
    },
    {
      id: "5",
      name: "Liam",
      surname: "Jones",
      email: "liam.jones@example.com",
      gpa: 3.4,
      favClasses: [],
    },
    {
      id: "6",
      name: "Olivia",
      surname: "Davis",
      email: "olivia.davis@example.com",
      gpa: 3.7,
      favClasses: [],
    },
    {
      id: "7",
      name: "Ethan",
      surname: "Miller",
      email: "ethan.miller@example.com",
      gpa: 3.6,
      favClasses: [],
    },
    {
      id: "8",
      name: "Ava",
      surname: "Wilson",
      email: "ava.wilson@example.com",
      gpa: 3.8,
      favClasses: [],
    },
    {
      id: "9",
      name: "Noah",
      surname: "Anderson",
      email: "noah.anderson@example.com",
      gpa: 3.5,
      favClasses: [],
    },
    {
      id: "10",
      name: "Mia",
      surname: "Garcia",
      email: "mia.garcia@example.com",
      gpa: 3.9,
      favClasses: [],
    },
    {
      id: "11",
      name: "Grace",
      surname: "Harris",
      email: "grace.harris@example.com",
      gpa: 3.6,
      favClasses: [],
      status: "pending",
    },
    {
      id: "12",
      name: "Elijah",
      surname: "Turner",
      email: "elijah.turner@example.com",
      gpa: 3.2,
      favClasses: [],
      status: "send",
    },
    {
      id: "13",
      name: "Aria",
      surname: "Wright",
      email: "aria.wright@example.com",
      gpa: 3.7,
      favClasses: [],
      status: "accepted",
    },
    {
      id: "14",
      name: "Logan",
      surname: "Parker",
      email: "logan.parker@example.com",
      gpa: 3.4,
      favClasses: [],
      status: "accepted",
    },
    {
      id: "15",
      name: "Sophie",
      surname: "Anderson",
      email: "sophie.anderson@example.com",
      gpa: 3.8,
      favClasses: [],
      status: "pending",
    },
  ];
  
  
  